# Project language
language: php

sudo: required

services:
  - docker

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0

script:
  - make all

# after_success:
#   - if [ "$TRAVIS_BRANCH" == "master" ]; then
#     make docker-publish;
#     fi

jobs:
  include:
    - stage: deploy
      script: make docker-publish
      php: 7.0
      if: branch = master
